# Generated by Django 4.1 on 2022-08-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pix',
            field=models.ImageField(blank=True, default=None, upload_to='profile/profile_photo'),
        ),
    ]
