# Generated by Django 4.1 on 2022-08-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_csvdocs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CsvDocs',
            new_name='CsvDoc',
        ),
    ]
