# Generated by Django 4.1 on 2022-08-26 02:47

import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_csvdoc_file_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='csvdoc',
            name='file_name',
            field=models.FileField(default=None, upload_to='files/csvs', validators=[contact.validators.file_validator]),
        ),
    ]
