# Generated by Django 4.1 on 2022-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_managers_alter_csvdoc_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_avatar',
            field=models.FileField(default='avatar.png', upload_to='contacts/avatar'),
        ),
    ]
